In [1]:
import pyreadr
import h5py
import numpy as np
import pandas as pd

In [2]:
def df2array(df):
    m,n = len(df.columns.levels[0]), len(df.columns.levels[1])
    arr = df.values.reshape(-1,m,n)
    return(arr)

In [29]:
soils = pyreadr.read_r('/home/rodrigo7/Documents/APSIMDL/original/grid10_horizons_v2_dt.rds')[None]
soils.ph.fillna(soils.ph.mean(), inplace = True)
soils

,id_tile,mukey,X,Y,top,bottom,thick,center,restriction,watertable,...,slope,sand,clay,wetbd,om,ksat,ll,dul,ph,CN2
0,4,1005959,-90.867230,41.045696,0.0,5.0,50.0,2.5,250.0,15.0,...,0.5,6.000000,24.000000,1.250000,5.000000,2.820000,17.000000,30.300000,6.500000,82.5
1,4,1005959,-90.867230,41.045696,5.0,10.0,50.0,7.5,250.0,15.0,...,0.5,6.000000,24.000000,1.250000,5.000000,2.820000,17.000000,30.300000,6.500000,82.5
2,4,1005959,-90.867230,41.045696,10.0,15.0,50.0,12.5,250.0,15.0,...,0.5,6.000000,24.000000,1.250000,5.000000,2.820000,17.000000,30.300000,6.500000,82.5
3,4,1005959,-90.867230,41.045696,15.0,20.0,50.0,17.5,250.0,15.0,...,0.5,6.050000,23.950000,1.253750,4.893750,2.820000,16.895000,30.227500,6.492500,82.5
4,4,1005959,-90.867230,41.045696,20.0,40.0,200.0,30.0,250.0,15.0,...,0.5,7.041667,22.958333,1.328125,2.786458,2.820000,14.812500,28.789583,6.343750,82.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34304,2,995995,-89.800952,42.166810,60.0,80.0,200.0,70.0,172.0,NaN,...,8.0,8.050895,32.752270,1.383460,0.599166,8.108197,18.470101,31.927910,6.235173,80.0
34305,2,995995,-89.800952,42.166810,80.0,100.0,200.0,90.0,172.0,NaN,...,8.0,11.331148,40.860656,1.393033,0.432787,5.524590,21.904918,33.776230,6.330328,80.0
34306,2,995995,-89.800952,42.166810,100.0,150.0,500.0,125.0,172.0,NaN,...,8.0,16.096721,52.540984,1.407049,0.199180,2.041150,26.857377,36.439344,6.470492,80.0
34307,2,995995,-89.800952,42.166810,150.0,200.0,500.0,175.0,172.0,NaN,...,8.0,17.100000,55.000000,1.410000,0.150000,2.301835,27.900000,37.000000,6.500000,80.0
34308,2,995995,-89.800952,42.166810,200.0,250.0,500.0,225.0,172.0,NaN,...,8.0,17.100000,55.000000,1.410000,0.150000,2.330000,27.900000,37.000000,6.500000,80.0

In [30]:
cls = ["slope_code", "slope", "sand", "clay", "wetbd", "om", "ksat", "ll", "dul", "ph", "CN2"]
soilsw = soils.pivot(index='mukey', columns='center', values = cls)
soilsw

        slope_code                                                        ...  \
center       2.5   7.5   12.5  17.5  30.0  50.0  70.0  90.0  125.0 175.0  ...
mukey                                                                     ...
1005959        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...
1014325        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...
1014869        3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0  ...
1015706        2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0  ...
1015756        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...
...            ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...
988903         2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0  ...
988907         1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...
991315         1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...
995175         1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...
995995         3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0  ...

          CN2
center  7.5   12.5  17.5  30.0  50.0  70.0  90.0  125.0 175.0 225.0
mukey
1005959  82.5  82.5  82.5  82.5  82.5  82.5  82.5  82.5  82.5  82.5
1014325  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5
1014869  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0
1015706  76.0  76.0  76.0  76.0  76.0  76.0  76.0  76.0  76.0  76.0
1015756  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
988903   84.0  84.0  84.0  84.0  84.0  84.0  84.0  84.0  84.0  84.0
988907   82.5  82.5  82.5  82.5  82.5  82.5  82.5  82.5  82.5  82.5
991315   78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5  78.5
995175   84.0  84.0  84.0  84.0  84.0  84.0  84.0  84.0  84.0  84.0
995995   80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0

[3119 rows x 121 columns]

In [31]:
# Dim1: Locations, Dim2: Variables, Dim3: Depth

# soilsnp = df2array(soilsw).astype('float32')

In [45]:
# data_file = '/home/rodrigo7/Documents/APSIMDL/data/train.h5'
# with h5py.File(data_file, mode='a') as hdf5_file:
#     hdf5_file.create_dataset("soils", data = soilsnp)

In [46]:
soilsw.to_hdf(data_file, "soils")